### ISSUE TITLE
Training Method for ShapeNet Data

### ISSUE THREAD

**Issue by ttm119** [Monnte/shape-completion#2]
I encounter an error while trying to train ShapeNet using the BaseComplete model, preventing the training from proceeding. Could you please explain the correct method to train ShapeNet?

creating data loader...
Loading data from ./datasets/shapenet/32/ and filtering with ./datasets/shapenet/val.txt
Missing counterparts: 0
Final dataset size: 0
Traceback (most recent call last):
  File "./scripts/train.py", line 119, in <module>
    main()
  File "./scripts/train.py", line 48, in main
    val_data_loader = load_data_loader(
  File "/mnt/sda1/shape-completion/model/datasets.py", line 118, in load_data_loader
    loader = DataLoader(
  File "/home/anaconda3/envs/shape-completion/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/anaconda3/envs/shape-completion/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by Monnte** [comment]
Hello,

you need to download the shapnet ground truth models from the [link](https://github.com/yuchenrao/PatchComplete/tree/main?tab=readme-ov-file#download-processed-datasets) provided in README, and then generate the dataset using [dataset_hole.py](https://github.com/Monnte/shape-completion/blob/main/dataset_processing/dataset_hole.py) script. Then use should have the complete and incomplete counterparts for the training. 

If you have done all of this and u still get the error, the problem is in the filtering when loading the models to dataset, adjust the file based on your needs.

If you need more help, feel free to ask.
